import { StyleSheet } from "react-native";

export const colors = {
  background: "#F8F9F5",
  surface: "#FFFFFF",
  text: "#182B23",
  muted: "#65736B",
  primary: "#226347",
  pale: "#EAF1E8",
  border: "#E0E7DE",
  amber: "#89601B",
  amberBg: "#FFF4DB",
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: {
    flexGrow: 1,
    width: "100%",
    maxWidth: 480,
    alignSelf: "center",
    padding: 24,
    paddingBottom: 40,
    gap: 24,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  stack: { gap: 12 },
  brand: {
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: -0.7,
    color: colors.primary,
  },
  tag: {
    color: colors.muted,
    fontSize: 11,
    letterSpacing: 1.5,
    fontWeight: "700",
  },
  title: {
    fontSize: 34,
    lineHeight: 45,
    fontWeight: "800",
    letterSpacing: -1.4,
    color: colors.text,
  },
  subtitle: { fontSize: 16, lineHeight: 25, color: colors.muted },
  label: { fontSize: 16, fontWeight: "700", color: colors.text },
  small: { fontSize: 13, lineHeight: 21, color: colors.muted },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 16,
  },
  notice: { backgroundColor: colors.amberBg, borderRadius: 14, padding: 14 },
  noticeText: { color: colors.amber, fontSize: 13, lineHeight: 21 },
  photo: {
    width: "100%",
    aspectRatio: 1.15,
    borderRadius: 22,
    backgroundColor: colors.pale,
  },
  input: {
    backgroundColor: colors.surface,
    color: colors.text,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    fontSize: 16,
    minHeight: 104,
    textAlignVertical: "top",
  },
  error: { backgroundColor: "#FCECE8", padding: 16, borderRadius: 14, gap: 6 },
  errorText: { color: "#923D30", fontSize: 14, lineHeight: 22 },
  divider: { height: 1, backgroundColor: colors.border },
});
